name: '🔸 Run tests 🧪'

on:
  workflow_call:

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: myparcelnl/actions/setup-app-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        if: github.actor != 'dependabot[bot]'
        with:
          token: ${{ steps.credentials.outputs.token }}

      - uses: myparcelnl/actions/build-docker-image-reg@v3
        if: github.actor != 'dependabot[bot]'
        id: docker
        with:
          image: ${{ github.owner }}//php-sdk
          target: test
          registry-user: ${{ github.actor }}
          registry-password: ${{ steps.credentials.outputs.token }}

      - name: 'Create .env file'
        run: |
          cat << EOF > .env
          CI=${CI}
          API_KEY_NL=${{ secrets.API_KEY_NL }}
          API_KEY_BE=${{ secrets.API_KEY_BE }}
          EOF

      - name: 'Run tests'
        if: github.actor != 'dependabot[bot]'
        run: docker run --env-file .env ${{ steps.docker.outputs.tagged-image }}

      - name: 'Get coverage file from container'
        if: github.actor != 'dependabot[bot]'
        run: docker cp $(docker ps -alq):/app/coverage.xml .

      - name: 'Update code coverage'
        if: github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v3
